(lecture02:homework02)=
# Homework 2

+ Type your name and email in the "Student details" section below.
+ Develop the code and generate the figures you need to solve the problems using this notebook.
+ For the answers that require a mathematical proof or derivation you can either:
    
    - Type the answer using the built-in latex capabilities. In this case, simply export the notebook as a pdf and upload it on gradescope; or
    - You can print the notebook (after you are done with all the code), write your answers by hand, scan, turn your response to a single pdf, and upload on gradescope.

+ The total homework points are 100. Please note that the problems are not weighed equally.

```{note}
+ This is due before the beginning of the next lecture.
+ Please match all the pages corresponding to each of the questions when you submit on gradescope.
```

## Student details

+ **First Name:** Connor
+ **Last Name:**Scargill
+ **Email:** pscargil@purdue.edu

## Problem 1 - Lists

Consider the following list:

In [11]:
data = [1, 4, 3, 10, 4, 3, 4, 4]

Add the element 6 at the end of `data`:

In [12]:
data.append(6)

Add the list [0, -1, 3] at the begining of `data`

In [13]:
data = [0, -1, 3] + data

How many elements are in the `data`?

In [14]:
len(data)

12

Extract all `data` elements from the second to the second to last (inclusive).

In [15]:
data[1:-1]

[-1, 3, 1, 4, 3, 10, 4, 3, 4, 4]

Extract all `data` elements from the second to the second to last (inclusive) skipping every other element.

In [16]:
data[1:-1:2]

[-1, 1, 3, 4, 4]

Sort the list.

In [17]:
data.sort()
data

[-1, 0, 1, 3, 3, 3, 4, 4, 4, 4, 6, 10]

Find the minimum of the list.

In [18]:
data[0]

-1

Find the average of the elements in the list.

In [19]:
sum(data)/len(data)

3.4166666666666665

## Problem 2 - Numerical Python

Let's make a random array:

In [20]:
import numpy as np
np.random.seed(12345) # We need this so that we get the same numbers
                      # every time we runt the following code
x = np.random.randn(100)
x

array([-2.04707659e-01,  4.78943338e-01, -5.19438715e-01, -5.55730304e-01,
        1.96578057e+00,  1.39340583e+00,  9.29078767e-02,  2.81746153e-01,
        7.69022568e-01,  1.24643474e+00,  1.00718936e+00, -1.29622111e+00,
        2.74991633e-01,  2.28912879e-01,  1.35291684e+00,  8.86429341e-01,
       -2.00163731e+00, -3.71842537e-01,  1.66902531e+00, -4.38569736e-01,
       -5.39741446e-01,  4.76985010e-01,  3.24894392e+00, -1.02122752e+00,
       -5.77087303e-01,  1.24121276e-01,  3.02613562e-01,  5.23772068e-01,
        9.40277775e-04,  1.34380979e+00, -7.13543985e-01, -8.31153539e-01,
       -2.37023165e+00, -1.86076079e+00, -8.60757398e-01,  5.60145293e-01,
       -1.26593449e+00,  1.19827125e-01, -1.06351245e+00,  3.32882716e-01,
       -2.35941881e+00, -1.99542955e-01, -1.54199553e+00, -9.70735912e-01,
       -1.30703025e+00,  2.86349747e-01,  3.77984111e-01, -7.53886535e-01,
        3.31285650e-01,  1.34974221e+00,  6.98766888e-02,  2.46674110e-01,
       -1.18616011e-02,  

Find the minimum of ``x``.

In [22]:
x.sort()
x[0]

np.float64(-2.3702316539567447)

Find the maximum of ``x``.

Find the maximum of ``x``.

In [23]:
x[-1]

np.float64(3.248943919430755)

Use ``x.shape`` to get the number of elements of ``x`` as an integer.

In [25]:
print(x.shape)

(100,)


Find the sum of all the elements of ``x`` divided by the number of elements of ``x``. This is the average.

In [26]:
sum(x)/x.shape

array([0.03361439])

Compare the average you found above with the result of ``x.mean()``. Are they the same?

In [29]:
x.mean()

np.float64(0.033614388208863914)

Yes they're the same

Square the elements of ``x`` and store them in a new array called ``x2``.

In [30]:
x2 = np.square(x)
x2

array([5.61799809e+00, 5.56685711e+00, 5.30949377e+00, 4.00655192e+00,
       3.46243071e+00, 2.39973076e+00, 2.37775021e+00, 1.77584863e+00,
       1.70832808e+00, 1.68018916e+00, 1.60259014e+00, 1.48425971e+00,
       1.34031436e+00, 1.13105873e+00, 1.04290566e+00, 9.95042655e-01,
       9.42328211e-01, 9.13685263e-01, 8.48551604e-01, 8.45041812e-01,
       7.40903299e-01, 6.90816205e-01, 5.68344907e-01, 5.60299479e-01,
       5.27386037e-01, 5.09145019e-01, 4.36292388e-01, 4.25715589e-01,
       3.87225211e-01, 3.33029755e-01, 3.08836171e-01, 2.91320828e-01,
       2.69816579e-01, 2.53096923e-01, 1.92343413e-01, 1.38266872e-01,
       4.19052259e-02, 3.98173910e-02, 1.73126651e-02, 1.32084922e-02,
       5.51936117e-04, 1.40697580e-04, 1.00639060e-04, 8.84122295e-07,
       4.92156418e-04, 8.76761120e-04, 2.50093568e-03, 2.63334221e-03,
       4.88275164e-03, 8.63187356e-03, 1.39499139e-02, 1.43585398e-02,
       1.54060911e-02, 2.33101359e-02, 3.54232602e-02, 4.96824244e-02,
      

Find the average of ``x2`` and subtract from it the square of average of ``x``.

In [32]:
x2.mean() - np.square(x.mean())

np.float64(1.0714002155166888)

Compare the result you found on the cell above with ``x.var()``. Are they the same? (Remark: You just calculated the empirical variance of the "data" ``x`` in two different ways!)

In [33]:
x.var()

np.float64(1.0714002155166888)

Yes they are the same